### ISSUE TITLE
I require understanding a few things about the code. New to R and nilm

### ISSUE THREAD

**Issue by SaeedArisha** [smarisa/sor-nilm#1]

**Comment by sjjsy** [comment]
Hi @SaeedArisha, pleased to hear of your interest toward R, NILM and this repository we have created. Unfortunately we haven't spent almost any time on ensuring others can easily understand, test and build upon this work. However, we made this public because it might be valuable for people who are very familiar with R and do research on energy disaggregation and/or hidden Markov models. However, even for those people it is likely that they need to invest quite some time to get grips with the algorithm, get it running properly and then build upon or otherwise utilize it.

I believe there are a lot more repositories in GitHub and other online resources that are more useful for you if you are new to R and NILM. Perhaps check eg. https://support.rstudio.com/hc/en-us/articles/201141096-Getting-Started-with-R and then start experimenting with the algorithms provided in the NILM toolkit: https://github.com/nilmtk/nilmtk

All the best!
